### ISSUE TITLE
Find a way to execute js code in yaml

### ISSUE THREAD

**Issue by micw** [firstandthird/load-grunt-config#148] opened 2016-03-08 16:09 UTC
In some situations it's required to execute code in configs. Example:
https://github.com/gruntjs/grunt-contrib-less#usage-examples - less requires some code to load plugins.

ATM it's not possible to describe that in yaml notation.

**Comment by SolomoN-ua** [comment] 2016-03-08 16:42
Hi @micw, also it is not possible to do that in JSON and I believe in CSON formats, it is not a bug of `load-grunt-config` this is specifics of those file formats.

If you want to specify code in your config files please use JS (or coffee) file formats instead.

Closing this issue, let me know if you have any other questions.

**Closed by SolomoN-ua** 2016-03-08 16:42 UTC

**Comment by micw** [comment] 2016-03-08 20:31
No, it's not a bug, it's a feature request (but github has only "issues", not bug/feature requests).

A way to implement this could be by convention, e.g.:
- <! code here !>

**Comment by SolomoN-ua** [comment] 2016-03-09 09:42
@micw ah, ok... but if to be honest I'm not sure that we should do this, as those file formats are not designed to keep code in it. It is much better to use js files for that purpose.
